version: '2'

volumes:
  data-postgres:
    external: true
  data-redis:
    external: true

services:
  postgres:
    image: postgres:12.6
    container_name: 'postgres'
    volumes:
      - data-postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mySecret160418
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=mySecret160418 pg_isready -U admin -d digi_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:3'
    container_name: 'redis'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - data-redis:/data
    ports:
      - 6379:6379
